### ISSUE TITLE
Result methods need more type hints

### ISSUE THREAD

**Issue by Artalus** [alice-biometrics/meiga#16]
This library is awesome and I am so glad I stumbled upon it before diving into writing something similar on my own :)

---

It feels to me that the core `Result[...]` class's methods kinda lack typization, making it harder to use with autocompletion and linters. For example:
```python
from typing import NamedTuple, cast

from meiga import Result, Error

class MyOutcome(NamedTuple):
    x: int

def foo(fail: bool) -> Result[MyOutcome, Error]:
    if fail:
        return Result(failure=Error())
    return Result(success=MyOutcome(x=11))

def test_type_check() -> None:
    a = foo(True)
    assert a.is_success
    av = a.unwrap_or_throw()
    assert av.x == 11
    assert cast(MyOutcome, av).x == 11
```

Here `av = a.unwrap_or_throw()` should provide me with `MyOutcome` - since its very semantic is to either return a valid result, or raise exception - but VS Code (and probably other editors and IDEs that integrate with mypy) shows that the type is actually `Any | None`. Furthermore, accessing `av.x` causes `x is not a known member of None` warning. I then have to use `cast(MyOutcome, av)` to get typing back on tracks.

If I understood it correctly, the problem arise because 
- `Result.unwrap_or_throw` is not annotated with type hints at all;
- `Result.throw` (used inside the former) throws on condition, making the type checker think "it usually returns `None`".

It seems that changing `unwrap_or_throw` to this:
```python
    def unwrap_or_throw(self) -> TS:
        if self._is_success:
            return cast(TS, self.value)
        raise self.value
```
fixes the problem, as the return type is specified and the raise is explicit.

I just chose `unwrap_or_throw()` as the simplest example; all other methods are untyped too - either causing "use of untyped function in typed context" warnings from mypy, or confusing it into thinking that the returned values are `Any` instead of success- or error-types specified in `Result[...]` hint.

**Comment by acostapazo** [comment]
First of all, thank you very much for your valuable feedback @Artalus , we really appreciate it :) 

Please, find in this [PR](https://github.com/alice-biometrics/meiga/pull/17), some of the improvement added to the code (following your advices 🥇 ).

We expect to release a new version soon with these and other minor improvements that we have noticed in the review.

Again, thanks for improving `meiga 🧙` package!
