### ISSUE TITLE
Warn user to add @early_return when use unwrap_or_return

### ISSUE THREAD

**Issue by acostapazo** [alice-biometrics/meiga#69]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I already read and followed all the [documentation](https://alice-biometrics.github.io/meiga/) and didn't find an answer.

### Description & Wanted Solution

The documentation currently provides guidance on using the unwrap_or_return option to minimize visual noise, as outlined here: [Meiga Documentation - unwrap_or_return](https://alice-biometrics.github.io/meiga/usage/result/#unwrap_or_return).

However, for users who may not be familiar with the meiga package, there's a potential oversight – the need to decorate the function with @early_return might be overlooked.

Suggestion:
To enhance user experience, it would be beneficial to include an alert or warning, explicitly prompting users to add the @early_return decorator when utilizing the unwrap_or_return option. This addition would serve as a helpful reminder and prevent potential oversight for those less familiar with the package.

### Wanted Code

```python
# @early_return # WHEN YOU FORGOT TO ADD THIS
def handling_result(key: str) -> Result:
    user_info = {"first_name": "Rosalia", "last_name": "De Castro", "age": 60}
    first_name = string_from_key(dictionary=user_info, key=key).unwrap_or_return()
    # Do whatever with the name
    name = first_name.lower()
    return Result(success=name)
```

**Comment by fgsalomon** [comment]
I don't think a runtime warning is feasible or practical. I think it would require using reflection and this could impact the performance. In case we can achieve a runtime warning it's possible that the developer won't see the warning message between the production logs.

I believe an approach based on static code analysis would be better like:

- PyCharm (Professional edition) allows creating [custom code inspections](https://www.jetbrains.com/help/pycharm/creating-custom-inspections.html). I think this would be fantastic but not useful in our organization.
- Custom linter rules
   - ruff [doesn't support them](https://github.com/astral-sh/ruff/issues/283) 😞 
   - flake8 does support them. Yeah, I know we are moving from flake8 to ruff but we could create our custom rule and use flake8 only to check the code against that rule
   
Attempt to create a custom rule for Flake8 [here](https://gist.github.com/fgsalomon/64788b1efbf8534c35d453c31198c6c4).

Example execution:
![image](https://github.com/alice-biometrics/meiga/assets/3149695/c8c16a97-806d-4c30-960d-a349c4b88ebd)

The approach is naïve and nested functions that use `unwrap_or_return` are false positives but I think it could be useful.

**Comment by acostapazo** [comment]
> I don't think a runtime warning is feasible or practical. I think it would require using reflection and this could impact the performance. In case we can achieve a runtime warning it's possible that the developer won't see the warning message amongst the production logs.

Agree. I was thinking on simpler solution. My proposal in https://github.com/alice-biometrics/meiga/pull/70. It tries to keep improving semantic and debug information as in https://github.com/alice-biometrics/meiga/pull/68.

The main ideas is, if you don't control the `unwrap_or_return` with a `@early_return`the `WaitingForEarlyReturn` (new semantic name proposal) will be raised and the user will have available some useful information in the exception.


> Attempt to create a custom rule for Flake8 [here](https://gist.github.com/fgsalomon/64788b1efbf8534c35d453c31198c6c4).

Awesome, I have never had the opportunity to deep into flake8 plugins and it could be very interesting to improve our dev experience. We can use both proposals.
